name: Log ISS Location Data Daily

# Trigger daily at 12:00 UTC + manual trigger
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  collect-iss-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3️⃣ Prime cache for pip dependencies
      - name: prime-cache-f85aaf1
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-f85aaf1
          restore-keys: cache-f85aaf1

      # 4️⃣ Install dependencies
      - name: Install requests
        run: pip install requests

      # 5️⃣ Fetch ISS data safely
      - name: Fetch ISS location data
        run: |
          python - << 'EOF'
          import requests

          try:
              data = requests.get('http://api.open-notify.org/iss-now.json', timeout=10).text
              with open('iss-location.jsonl', 'a') as f:
                  f.write(data + '\n')
          except Exception as e:
              print(f"Error fetching ISS data: {e}")
          EOF

      # 6️⃣ Commit and push only if file changed
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add iss-location.jsonl
          if ! git diff --cached --quiet; then
              git commit -m "Update ISS position data [skip ci]"
              git push
          else
              echo "No changes to commit"
          fi
